/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc.assignment.view;

import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import pdc.assignment.model.Locations;
import pdc.assignment.pkg2.HibernateUtil;
import pdc.assignment.services.LocationManagement;
/**
 *
 * @author dhy6184
 */
public class AddLocation extends javax.swing.JPanel {
    
    private JFrame parentFrame;
    private LocationManagement locationManagement;

    /**
     * Creates new form AddLocation
     */
    public AddLocation(JFrame parentFrame) {
        this.locationManagement = new LocationManagement();
        this.parentFrame = parentFrame;
        initComponents();
        // Set minimum size for the parent frame
        parentFrame.setMinimumSize(new Dimension(850, 690));
        // Add a ComponentListener to limit resizing
        parentFrame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int width = parentFrame.getWidth();
                int height = parentFrame.getHeight();
                if (width < 850 || height < 690) {
                    parentFrame.setSize(Math.max(width, 850), Math.max(height, 690));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLocationName = new javax.swing.JTextField();
        addLocationNameLabel = new javax.swing.JLabel();
        addLocationConfirm = new javax.swing.JButton();
        addLocationBack = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addLocationAddressLabel = new javax.swing.JLabel();
        addLocationAddress = new javax.swing.JTextField();

        addLocationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationNameActionPerformed(evt);
            }
        });

        addLocationNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addLocationNameLabel.setText("Location Name:");

        addLocationConfirm.setText("Confirm");
        addLocationConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationConfirmActionPerformed(evt);
            }
        });

        addLocationBack.setText("Go back");
        addLocationBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationBackActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("What is the name of the location you want to add?");

        addLocationAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addLocationAddressLabel.setText("Location Address:");

        addLocationAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addLocationBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addLocationConfirm))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addLocationAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addLocationNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addLocationAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(addLocationName))))
                        .addContainerGap(213, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLocationNameLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLocationAddressLabel)
                    .addComponent(addLocationAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLocationBack)
                    .addComponent(addLocationConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLocationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addLocationNameActionPerformed

    private void addLocationConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationConfirmActionPerformed
        // TODO add your handling code here:
        String name = addLocationName.getText().trim();
        String address = addLocationAddress.getText().trim();

        // Check if both name and address are not empty
        if (!name.isEmpty() && !address.isEmpty()) {
            Locations location = new Locations();
            location.setName(name);
            location.setAddress(address); // Set the address

            boolean added = locationManagement.addLocation(location);
            if (added) {
                JOptionPane.showMessageDialog(this, "Location added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add location. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter both name and address for the location.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addLocationConfirmActionPerformed

    
    private void addLocationBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationBackActionPerformed
        // TODO add your handling code here:
        
        JFrame locationPanelFrame = new JFrame("Location Panel");
        locationPanelFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        locationPanelFrame.setSize(850, 690);
        locationPanelFrame.add(new LocationPanel(locationPanelFrame));
        locationPanelFrame.setLocationRelativeTo(null); //center the frame
        locationPanelFrame.setVisible(true);

        parentFrame.dispose(); //close panel
    }//GEN-LAST:event_addLocationBackActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program?", "Exit Program",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            //perform any cleanup or saving operations if needed

            //close the main window or exit the application
            Window window = SwingUtilities.getWindowAncestor(this);
            window.dispose(); //closes
            HibernateUtil.shutdown();
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void addLocationAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLocationAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addLocationAddress;
    private javax.swing.JLabel addLocationAddressLabel;
    private javax.swing.JButton addLocationBack;
    private javax.swing.JButton addLocationConfirm;
    private javax.swing.JTextField addLocationName;
    private javax.swing.JLabel addLocationNameLabel;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
