/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc.assignment.view;

import java.awt.Dimension;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pdc.assignment.model.Locations;
import pdc.assignment.services.LocationInterface;
import pdc.assignment.services.LocationManagement;

/**
 *
 * @author klinsmann
 */
public class LocationPanel extends javax.swing.JPanel {

    private JFrame parentFrame;

    /**
     * Creates new form Location
     */
    public LocationPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        setLocationList();
    }
    
    private static Locations locationToItem = null;

    public List<String> locationsToStrings(List<Locations> locations) {
        List<String> strings = new ArrayList<>();
        for (Locations location : locations) {
            strings.add(location.getName());
        }
        return strings;
    }
    
    private void setLocationList() {
        LocationInterface loc = new LocationManagement();
        List<Locations> locations = loc.browseLocations();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        List<String> locationStrings = locationsToStrings(locations);
        for (String locationString : locationStrings) {
            listModel.addElement(locationString);
        }
        locationlist.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeLocation = new javax.swing.JButton();
        selectLocation = new javax.swing.JButton();
        addLocation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationlist = new javax.swing.JList<>();
        locationlistlabel = new javax.swing.JLabel();
        exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        removeLocation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        removeLocation.setText("Remove a Location");
        removeLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLocationActionPerformed(evt);
            }
        });

        selectLocation.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        selectLocation.setText("Select a Location");
        selectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLocationActionPerformed(evt);
            }
        });

        addLocation.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        addLocation.setText("Add a Location");
        addLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationActionPerformed(evt);
            }
        });

        locationlist.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        locationlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        locationlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(locationlist);

        locationlistlabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        locationlistlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locationlistlabel.setText("Location");

        exit1.setText("Exit");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Location Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(locationlistlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit1)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(locationlistlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(removeLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(selectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(exit1)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationActionPerformed
        // TODO add your handling code here:

        JFrame addLocationFrame = new JFrame("Add new location");
        addLocationFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addLocationFrame.setSize(850, 690); //window size of addlocation.java
        addLocationFrame.add(new AddLocation(addLocationFrame));
        addLocationFrame.setLocationRelativeTo(null); //center the frame FRAME PLACEMENT
        addLocationFrame.setVisible(true);

        parentFrame.dispose();
    }//GEN-LAST:event_addLocationActionPerformed

    private void removeLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLocationActionPerformed
        // TODO add your handling code here:

        JFrame removeLocationFrame = new JFrame("Remove a location");
        removeLocationFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        removeLocationFrame.setSize(850, 690); //window size of addlocation.java
        removeLocationFrame.add(new RemoveLocation(removeLocationFrame));
        removeLocationFrame.setLocationRelativeTo(null); //center the frame FRAME PLACEMENT
        removeLocationFrame.setVisible(true);

        parentFrame.dispose();
    }//GEN-LAST:event_removeLocationActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit the program?", "Exit Program",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            //perform any cleanup or saving operations if needed

            //close the main window or exit the application
            Window window = SwingUtilities.getWindowAncestor(this);
            window.dispose(); //closes
            System.exit(0);
        }
    }//GEN-LAST:event_exit1ActionPerformed

    private void selectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLocationActionPerformed
        // TODO add your handling code here:
        if(locationToItem != null){
        JFrame frame = new JFrame("Item Panel");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //set the preffered size of window
        frame.setPreferredSize(new Dimension(850, 690));

        //set minimum size of window
        frame.setMinimumSize(new Dimension(850, 690));
        
        frame.getContentPane().add(new ItemPanel(locationToItem,frame));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        parentFrame.dispose(); //close panel
        
        }else{
        JOptionPane.showMessageDialog(this, "Please Select A Location", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_selectLocationActionPerformed

    private void locationlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationlistMouseClicked
        // TODO add your handling code here:
        String selectedLocation = locationlist.getSelectedValue();
        System.out.println(selectedLocation);
        LocationInterface loc = new LocationManagement();
        locationToItem = loc.loadLocation(selectedLocation);
    }//GEN-LAST:event_locationlistMouseClicked

    public static void main(String[] args) {
        JFrame frame = new JFrame("Location Panel");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //set the preffered size of window
        frame.setPreferredSize(new Dimension(850, 690));

        //set minimum size of window
        frame.setMinimumSize(new Dimension(850, 690));

        frame.getContentPane().add(new LocationPanel(frame));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLocation;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> locationlist;
    private javax.swing.JLabel locationlistlabel;
    private javax.swing.JButton removeLocation;
    private javax.swing.JButton selectLocation;
    // End of variables declaration//GEN-END:variables
}
