/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc.assignment.view;

import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import pdc.assignment.model.Locations;
import pdc.assignment.pkg2.HibernateUtil;
import pdc.assignment.services.LocationInterface;
import pdc.assignment.services.LocationManagement;

/**
 *
 * @author klinsmann
 */
public class RemoveLocation extends javax.swing.JPanel {

    private JFrame parentFrame;
    /**
     * Creates new form RemoveLocation
     */
    public RemoveLocation(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        
        parentFrame.setMinimumSize(new Dimension(850, 690));
        // Add a ComponentListener to limit resizing
        parentFrame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int width = parentFrame.getWidth();
                int height = parentFrame.getHeight();
                if (width < 850 || height < 690) {
                    parentFrame.setSize(Math.max(width, 850), Math.max(height, 690));
                }
            }
        });
        
        loadLocations();
    }
    
        private void loadLocations() {
        LocationInterface loc = new LocationManagement();
        //populate removeLocationDropdown with actual location names from database
        List<Locations> locations = loc.browseLocations();
        if (locations != null) {
            for (Locations location : locations) {
                removeLocationDropdown.addItem(location.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeLocationLabel = new javax.swing.JLabel();
        removeLocationDropdown = new javax.swing.JComboBox<>();
        removeLocationBack = new javax.swing.JButton();
        removeLocationConfirm = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        removeLocationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeLocationLabel.setText("Select a location to remove");

        removeLocationDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLocationDropdownActionPerformed(evt);
            }
        });

        removeLocationBack.setText("Go back");
        removeLocationBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLocationBackActionPerformed(evt);
            }
        });

        removeLocationConfirm.setText("Confirm");
        removeLocationConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLocationConfirmActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Which location do you want to remove?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(removeLocationBack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeLocationConfirm))
                                    .addComponent(removeLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(removeLocationDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addContainerGap(230, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeLocationDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeLocationBack)
                    .addComponent(removeLocationConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeLocationDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLocationDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeLocationDropdownActionPerformed

    private void removeLocationBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLocationBackActionPerformed
        // TODO add your handling code here:

        JFrame locationPanelFrame = new JFrame("Location Panel");
        locationPanelFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        locationPanelFrame.setSize(850, 690);
        locationPanelFrame.add(new LocationPanel(locationPanelFrame));
        locationPanelFrame.setLocationRelativeTo(null); //center the frame
        locationPanelFrame.setVisible(true);

        parentFrame.dispose(); //close panel
    }//GEN-LAST:event_removeLocationBackActionPerformed

    private void removeLocationConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLocationConfirmActionPerformed
        // TODO add your handling code here:
        LocationInterface loc = new LocationManagement();

        String selectedLocationName = (String) removeLocationDropdown.getSelectedItem();

            if (selectedLocationName != null && !selectedLocationName.isEmpty()) {
                Locations location = loc.loadLocation(selectedLocationName);
                if (location != null) {
                    boolean removalSuccessful = loc.deleteLocation(location); // Call a method to remove the item

                    if (removalSuccessful) {
                        // Show a success message
                        JOptionPane.showMessageDialog(this, "Location removed successfully!");
                    } else {
                        // Show a failure message
                        JOptionPane.showMessageDialog(this, "Failed to remove Location. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    // Show an error message if no item is selected
                    JOptionPane.showMessageDialog(this, "Please select an Loccation to remove.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }     
    }//GEN-LAST:event_removeLocationConfirmActionPerformed

    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program?", "Exit Program",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            //perform any cleanup or saving operations if needed

            //close the main window or exit the application
            Window window = SwingUtilities.getWindowAncestor(this);
            window.dispose(); //closes
            HibernateUtil.shutdown();
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeLocationBack;
    private javax.swing.JButton removeLocationConfirm;
    private javax.swing.JComboBox<String> removeLocationDropdown;
    private javax.swing.JLabel removeLocationLabel;
    // End of variables declaration//GEN-END:variables
}
