/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc.assignment.view;

import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import pdc.assignment.model.Items;
import pdc.assignment.model.Locations;
import pdc.assignment.pkg2.HibernateUtil;
import pdc.assignment.services.ItemInterface;
import pdc.assignment.services.ItemManagement;

/**
 *
 * @author klinsmann
 */
public class RemoveItem extends javax.swing.JPanel {

    private JFrame parentFrame;
    private final Locations location;

    /**
     * Creates new form RemoveItem
     *
     * @param location
     */
    public RemoveItem(Locations location, JFrame parentFrame) {
        this.location = location;
        this.parentFrame = parentFrame;
        initComponents();

        parentFrame.setMinimumSize(new Dimension(850, 690));
        // Add a ComponentListener to limit resizing
        parentFrame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int width = parentFrame.getWidth();
                int height = parentFrame.getHeight();
                if (width < 850 || height < 690) {
                    parentFrame.setSize(Math.max(width, 850), Math.max(height, 690));
                }
            }
        });
        loadItems();
    }
    
     private void loadItems() {
         ItemInterface it = new ItemManagement();
        //populate removeItemsDropdown
        List<Items> items = it.browseItemsByLocation(location);
        if (items != null) {
            for (Items item : items) {
                removeItemDropdown.addItem(item.getName());
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeItemLabel = new javax.swing.JLabel();
        removeItemDropdown = new javax.swing.JComboBox<>();
        removeItemBack = new javax.swing.JButton();
        removeItemConfirm = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        removeItemLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeItemLabel.setText("Select an item to remove");

        removeItemDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemDropdownActionPerformed(evt);
            }
        });

        removeItemBack.setText("Go back");
        removeItemBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemBackActionPerformed(evt);
            }
        });

        removeItemConfirm.setText("Confirm");
        removeItemConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemConfirmActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("What item do you want to remove?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeItemBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeItemConfirm))
                            .addComponent(removeItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(removeItemDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(232, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeItemDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeItemBack)
                    .addComponent(removeItemConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeItemDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemDropdownActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_removeItemDropdownActionPerformed

    private void removeItemBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemBackActionPerformed
        // TODO add your handling code here:

        JFrame itemPanelFrame = new JFrame("Item Panel");
        itemPanelFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        itemPanelFrame.setSize(850, 690);
        itemPanelFrame.add(new ItemPanel(location, itemPanelFrame));
        itemPanelFrame.setLocationRelativeTo(null); //center the frame
        itemPanelFrame.setVisible(true);

        parentFrame.dispose(); //close panel
    }//GEN-LAST:event_removeItemBackActionPerformed

    private void removeItemConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemConfirmActionPerformed
        // TODO add your handling code here:
        String itemName = (String) removeItemDropdown.getSelectedItem();
        ItemInterface it = new ItemManagement();
        Items removedItem = it.itemLoad(itemName, location);
        if (location != null) {
                    boolean removalSuccessful = it.deleteItem(removedItem); // Call a method to remove the item

                    if (removalSuccessful) {
                        // Show a success message
                        JOptionPane.showMessageDialog(this, "Item removed successfully!");
                    } else {
                        // Show a failure message
                        JOptionPane.showMessageDialog(this, "Failed to remove Item. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    // Show an error message if no item is selected
                    JOptionPane.showMessageDialog(this, "Please select an item to remove.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
    }//GEN-LAST:event_removeItemConfirmActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit the program?", "Exit Program",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            //perform any cleanup or saving operations if needed

            //close the main window or exit the application
            Window window = SwingUtilities.getWindowAncestor(this);
            window.dispose(); //closes
            HibernateUtil.shutdown();
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeItemBack;
    private javax.swing.JButton removeItemConfirm;
    private javax.swing.JComboBox<String> removeItemDropdown;
    private javax.swing.JLabel removeItemLabel;
    // End of variables declaration//GEN-END:variables
}
