/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdc.assignment.view;

import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pdc.assignment.model.Locations;

/**
 *
 * @author klinsmann
 */
public class SearchItems extends javax.swing.JPanel {
    private final Locations location;
    private JFrame parentFrame;
    /**
     * Creates new form SearchItems
     */
    public SearchItems(Locations location,JFrame parentFrame) {
        this.location = location;
        this.parentFrame = parentFrame;
        initComponents();
                
        parentFrame.setMinimumSize(new Dimension(850, 690));
        // Add a ComponentListener to limit resizing
        parentFrame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int width = parentFrame.getWidth();
                int height = parentFrame.getHeight();
                if (width < 850 || height < 690) {
                    parentFrame.setSize(Math.max(width, 850), Math.max(height, 690));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchItemBack = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchByName = new javax.swing.JButton();
        searchByQuantity = new javax.swing.JButton();
        searchByPrice = new javax.swing.JButton();

        searchItemBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchItemBack.setText("Go back");
        searchItemBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemBackActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Search for an item");

        searchByName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchByName.setText("Search by Name");
        searchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByNameActionPerformed(evt);
            }
        });

        searchByQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchByQuantity.setText("Search by Quantity");
        searchByQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByQuantityActionPerformed(evt);
            }
        });

        searchByPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchByPrice.setText("Search by Price");
        searchByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(searchByName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchByQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchByPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchItemBack))))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(searchByName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(searchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(searchByQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(searchItemBack)
                .addGap(27, 27, 27)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchItemBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemBackActionPerformed
        // TODO add your handling code here:

        JFrame itemPanelFrame = new JFrame("Item Panel");
        itemPanelFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        itemPanelFrame.setSize(850, 690);
        itemPanelFrame.add(new ItemPanel(location,itemPanelFrame));
        itemPanelFrame.setLocationRelativeTo(null); //center the frame
        itemPanelFrame.setVisible(true);

        parentFrame.dispose(); //close panel
    }//GEN-LAST:event_searchItemBackActionPerformed

    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to exit the program?", "Exit Program",
            JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            //perform any cleanup or saving operations if needed

            //close the main window or exit the application
            Window window = SwingUtilities.getWindowAncestor(this);
            window.dispose(); //closes
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void searchByQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByQuantityActionPerformed
        // TODO add your handling code here:
                
        JFrame searchByQuantityFrame = new JFrame("Add new item");
        searchByQuantityFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        searchByQuantityFrame.setSize(850, 690);
        searchByQuantityFrame.add(new SearchByQuantity(location,searchByQuantityFrame));
        searchByQuantityFrame.setLocationRelativeTo(null); //center the frame
        searchByQuantityFrame.setVisible(true);      
          
        parentFrame.dispose(); // close panel
    }//GEN-LAST:event_searchByQuantityActionPerformed

    private void searchByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByPriceActionPerformed
        // TODO add your handling code here:
                
        JFrame searchByPriceFrame = new JFrame("Add new item");
        searchByPriceFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        searchByPriceFrame.setSize(850, 690);
        searchByPriceFrame.add(new SearchByPrice(location, searchByPriceFrame));
        searchByPriceFrame.setLocationRelativeTo(null); //center the frame
        searchByPriceFrame.setVisible(true);      
          
        parentFrame.dispose(); // close panel
    }//GEN-LAST:event_searchByPriceActionPerformed

    private void searchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByNameActionPerformed
        // TODO add your handling code here:
                
        JFrame searchByNameFrame = new JFrame("Add new item");
        searchByNameFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        searchByNameFrame.setSize(850, 690);
        searchByNameFrame.add(new SearchByName(location,searchByNameFrame));
        searchByNameFrame.setLocationRelativeTo(null); //center the frame
        searchByNameFrame.setVisible(true);      
          
        parentFrame.dispose(); // close panel
    }//GEN-LAST:event_searchByNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchByName;
    private javax.swing.JButton searchByPrice;
    private javax.swing.JButton searchByQuantity;
    private javax.swing.JButton searchItemBack;
    // End of variables declaration//GEN-END:variables
}
